### ISSUE TITLE
Mark homework1, exercise 3 Mingyi, YANG

### ISSUE THREAD

**Issue by Yummy2016** [Yummy2016/stat679work#3]
Hi, Professor @cecileane ,
The SHA is:
https://github.com/Yummy2016/stat679work/commit/456c1095a7d65bad5e3e8df29f8446535359f1a2
I have updated the files in hw1/ in several parts:
- Extended the Readme.md file in the hw1/ folder
- Wirte down the shell scripts for exercise 3 in scripts/New.sh
- Add a tag to the old version so that I can check that anytime in the future
- As advised, I redirect the results of exercise2 into the results/ folder.
- Removed the .Rhistory in the folder

Thanks for your patient and valuable feedback of the previous homework :) If there are any problems of my new homework, I'm willing to know about that.

Best regards,
Mingyi

**Comment by Yummy2016** [comment]
Hi, Professor @cecileane ,
I haven't received any feedback from Pablo until now...On yesterday's class, I talked to him and we found that he ignored my previous invitation as a collaborator. I added him as my collaborator again yesterday so I guess maybe he is still working on the feedback...
I just want to let you know about that because I'm afraid that the delaying of the feedback will influence his performance in the grades...
If there are anything need me to do about that, let me know please :)
Thanks!
Best,
Mingyi

**Comment by pgonzalez6** [comment]
Hi Mingyi,

My apologies for the delay, last night I was really busy and I could not review your code. I must say that the codes I've been looking, this is the most organized and clear that I have seen, very good job, congratulations! It has several resources to reduce the extension of the script, surely I will use some of them in my script to make it a little more efficient. Honestly I can not find changes or errors which can improve the output or efficiency of the same, maybe you could be better as a presentation of the table to put fewer decimal variable CPU time, since it is a bit extensive. in my opinion is clear and legible description of the steps that were made and command lines can be interpreted easily by someone outside the course. Thank you very much for sharing your work with the rest. Best, Pablo.
