### ISSUE TITLE
Mark homework1, exercise3 Mingyi, YANG

### ISSUE THREAD

**Issue by Yummy2016** [Yummy2016/stat679work#4]
Hi,
The SHA is:
456c109
I have updated the files in hw1/ in several parts:
- Extended the Readme.md file in the hw1/ folder
- Wrote down the shell scripts for exercise 3 in scripts/New.sh
- Added a tag to the old version so that I can check that anytime in the future
- As advised, I redirected the results of exercise2 into the results/ folder. And also, I removed away the .Rhistory in the folder

If there are any problems of my new homework, I'm willing to know about that. Looking forward to your feedback :)
@BaconZhou 
@pgonzalez6

Best regards,
Mingyi

**Comment by BaconZhou** [comment]
Hi, Mingyi,

Nice script!! I have learn some other ways to extract the interested statistics, especially about how to use `bc` command, because I tried `bc` at first in my script, but couldn't find the right way to do the last question...

There is a tiny problem about **summary.csv** file, you may need to delete all the `space` in your file, otherwise it is not a strict ***.csv(Comma-separated values)** file... May be try `sed s/[:space:]//g summary.csv > new.csv`. I found this, because I also made the same mistake in first homework.

Overall, it is a great repo, nice job!

Best,
Peigen

**Comment by BaconZhou** [comment]
# code: excellent=+1, satisfactory=0, needs work=-1
name,performance,strategy,style,documentation,creativity,submission
Mingyi,+1,+1,+1,+1,+1,+1
