### ISSUE TITLE
Mark homework2, Mingyi Yang

### ISSUE THREAD

**Issue by Yummy2016** [Yummy2016/stat679work#6]
Hi,Professor @cecileane,
 The SHA is:
https://github.com/Yummy2016/stat679work/commit/4538a0bf9e94c2589fbcece050fd66b5ff94a816
I've uploaded my homework2 in the hw2/ folder, in this folder:

- data/ contains the datasets I downloaded from the coursedata/ on github

- script/ contains the .py file that I wrote for this project, and I also added the ipython notebook in this folder.

- results/ contains the result merged.csv generated by the codes.

If there are anything needs me to modify, let me know and I'm willing to know about that :)

Thanks!

Best,
Mingyi

**Comment by cecileane** [comment]
Hi Mingyi,

Excellent job! Your work was easy to go through, and your function worked. More details below.

## overall presentation

Your readme file is extensive, you show how to use it if one has data from several months, this is great. Your work is organized with different directories for the scripts and input/output files.

There is no need to format your csv file `merged.csv` as a table in markdown style: github will show a well-formatted csv file very nicely. In other words, it will do the conversion to html from csv directly, to view on the browser.

## running your script

It runs great within Python, and you provide excellent explanations to do in various ways. The downside of having to use your function interactively is that we can't use it with one shell command line. So if I wanted to use it as part of a larger workflow, that would be a problem. If I need to use your function once a month, it is great that it asks me a question to append or overwrite a file. But having an interactive question/answer does not work in a pipeline when we want to automate everything.

To run your script `6791_hw2_update.py`, I had to change its name so that it didn't start with a number, to import it as a module. I renamed it `hw2.py`. Then I could use your function with different file names by calling your function within Python. When I used your function straight from the box like this:

```python
import hw2 as h
twomonths = {'Jan':["waterTemperature.csv","energy.csv","merged.csv"], 'Feb':["waterTemperature.csv","energy.csv","merged.csv"]}
h.main(**twomonths)
```

Unfortunately, with a dictionary, the keys are not guaranteed to stay in the same order as they are input initially. In the example above, February files are treated before January files, unfortunately:

```python
>>> twomonths
{'Feb': ['waterTemperature.csv', 'energy.csv', 'merged.csv'], 'Jan': ['waterTemperature.csv', 'energy.csv', 'merged.csv']}
```

so using a list instead of a dictionary would have been a better choice, especially given that you don't use the keys themselves (you use the file names only).

## about your code

All of your code is contained in a single function. It works well, but it is better to break down your code into smaller functions. It makes it easier to test small blocks of code (to debug), easier for humans to understand the code, and easier to re-use smaller blocks of code later down the road. I know that you won't be re-using pieces of this particular function, but later in your career, it's quite typical that work that you do in November or January could re-use pieces of code that you wrote in October.

For example, one function could take the energy file name as input, open this energy file, and return the lists `date` and `energy`. A different function could open the temperature file, etc.

You could also have a function to write the output to some file handle, with or without the header: it would do what is repeated 4 times: on lines 138-143, again 150-152, and again 155-160, and again 164-169.

You don't really need the 2 stars in your function argument: `main(**filenames)`. The stars `**` let the function accept any number of arguments, possibly given by keywords (like: `main(a=1, b="hello")`). But you assume a single argument anyway (a dictionary). So having `main(filenames)` should work just as well.

You use docstrings at the beginning of key blocks (like `with open()` or for loops), which is great to comment your code. But at these places, comments would do just as well, because docstrings are used to build the help pages only when they are at the beginning of functions, or at the beginning of a file for a module, or at the beginning of a class definition. Your function, on the other hand, starts with a comment instead of a docstring.

Great use of regular expressions to parse the dates, which you compile first!

Your variables could have better names.
- `keys` is not a good name, because `keys()` is a function that applies to dictionaries
- `x` is not descriptive (line 10); you could have chosen something like `Nfiles` or `numFiles`.
- `first` `second` and `third` are not descriptive either, when we see that they are on 3 consecutive lines. `tempFN` `energyFN` and `outputFN` would have been better. I added "FN" for File Name, because you have a variable called `energy` later.
- `pre_d`, `d` and `e` are also not helpful.

Try to choose more descriptive names in the future to make your code more human-readable. Remember to write code for humans!

It's great that you checked that dates are sorted, unexpected date format, and for date overlap between the 2 data types.

Great job overall!
